/**
 * Frontier — Journal Modal (Save/Load + Ledger)
 *
 * Two tabs:
 *   - "Saves": slot management, JSON export/import (original functionality)
 *   - "Ledger": browse 5-day narrative summaries generated by the Director
 *
 * Visible when showSaveLoadModal is true AND dailyCyclePhase is 'idle'.
 * Slot 0 is auto-save (load only). Slots 1-3 are manual.
 */

import { useState, useEffect, useCallback } from 'react';
import { useStore } from '@/store';
import {
  selectShowSaveLoadModal,
  selectDailyCyclePhase,
  selectStructuredLedger,
} from '@/store/selectors';
import { useEscapeClose } from '@/ui/hooks/useEscapeClose';
import type { SaveSlotMeta } from '@/persistence/save-load';
import type { LedgerEntry } from '@/types/narrative';
import { colors } from '@/ui/theme';

type Tab = 'saves' | 'ledger';
type ConfirmAction = { type: 'load' | 'delete'; slot: number } | null;

export default function SaveLoadModal() {
  const show = useStore(selectShowSaveLoadModal);
  const phase = useStore(selectDailyCyclePhase);
  const ledger = useStore(selectStructuredLedger);
  const [tab, setTab] = useState<Tab>('saves');
  const [slots, setSlots] = useState<(SaveSlotMeta | null)[]>([null, null, null, null]);
  const [confirm, setConfirm] = useState<ConfirmAction>(null);
  const [busy, setBusy] = useState(false);
  const [expandedEntry, setExpandedEntry] = useState<number | null>(null);

  const loadSlots = useCallback(async () => {
    const { getSaveSlots } = await import('@/persistence/save-load');
    const metas = await getSaveSlots();
    const result: (SaveSlotMeta | null)[] = [null, null, null, null];
    for (const m of metas) {
      if (m.slot >= 0 && m.slot <= 3) result[m.slot] = m;
    }
    setSlots(result);
  }, []);

  useEffect(() => {
    if (show && phase === 'idle') {
      loadSlots();
    }
  }, [show, phase, loadSlots]);

  const isOpen = show && phase === 'idle';

  const close = useCallback(() => {
    useStore.getState().toggleSaveLoadModal();
    setConfirm(null);
    setExpandedEntry(null);
  }, []);

  useEscapeClose(isOpen, close);

  if (!isOpen) return null;

  const handleSave = async (slot: number) => {
    setBusy(true);
    try {
      const { saveGame } = await import('@/persistence/save-load');
      await saveGame(slot);
      await loadSlots();
      useStore.getState().setToast('Game saved', 'success');
    } catch {
      useStore.getState().setToast('Save failed', 'error');
    } finally {
      setBusy(false);
    }
  };

  const handleLoad = async (slot: number) => {
    setBusy(true);
    try {
      const { loadGame } = await import('@/persistence/save-load');
      const ok = await loadGame(slot);
      if (ok) {
        close();
      } else {
        useStore.getState().setToast('Load failed', 'error');
      }
    } catch {
      useStore.getState().setToast('Load failed', 'error');
    } finally {
      setBusy(false);
    }
  };

  const handleDelete = async (slot: number) => {
    setBusy(true);
    try {
      const { deleteSaveSlot } = await import('@/persistence/save-load');
      await deleteSaveSlot(slot);
      await loadSlots();
    } finally {
      setBusy(false);
      setConfirm(null);
    }
  };

  const handleExport = async () => {
    const { exportToJSON } = await import('@/persistence/save-load');
    const json = exportToJSON();
    const blob = new Blob([json], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `frontier-save-${new Date().toISOString().slice(0, 10)}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleImport = () => {
    const input = document.createElement('input');
    input.type = 'file';
    input.accept = '.json';
    input.onchange = async (e) => {
      const file = (e.target as HTMLInputElement).files?.[0];
      if (!file) return;
      const text = await file.text();
      const { importFromJSON } = await import('@/persistence/save-load');
      const ok = importFromJSON(text);
      if (ok) {
        close();
      } else {
        useStore.getState().setToast('Import failed — invalid save file', 'error');
      }
    };
    input.click();
  };

  const confirmAction = async () => {
    if (!confirm) return;
    if (confirm.type === 'load') await handleLoad(confirm.slot);
    if (confirm.type === 'delete') await handleDelete(confirm.slot);
    setConfirm(null);
  };

  return (
    <div style={styles.overlay} className="frontier-overlay">
      <div style={styles.card} className="frontier-overlay-card">
        <div style={styles.header}>
          <h2 style={styles.title}>Journal</h2>
          <button type="button" style={styles.closeBtn} onClick={close} aria-label="Close journal">X</button>
        </div>

        {/* Tab bar */}
        <div style={styles.tabBar}>
          <button
            type="button"
            style={tab === 'saves' ? styles.tabActive : styles.tab}
            onClick={() => setTab('saves')}
          >
            Saves
          </button>
          <button
            type="button"
            style={tab === 'ledger' ? styles.tabActive : styles.tab}
            onClick={() => setTab('ledger')}
          >
            Ledger{ledger.length > 0 ? ` (${ledger.length})` : ''}
          </button>
        </div>

        {/* Saves tab */}
        {tab === 'saves' && (
          <>
            <div style={styles.slotList}>
              {slots.map((meta, idx) => (
                <div key={idx} style={styles.slotRow}>
                  <div style={styles.slotInfo}>
                    <span style={styles.slotLabel}>
                      {idx === 0 ? 'Auto-Save' : `Slot ${idx}`}
                    </span>
                    {meta ? (
                      <span style={styles.slotMeta}>
                        {meta.waypoint} &middot; {meta.totalMiles}mi &middot; Day {meta.daysElapsed} &middot;{' '}
                        {new Date(meta.timestamp).toLocaleDateString()}
                      </span>
                    ) : (
                      <span style={styles.slotEmpty}>Empty</span>
                    )}
                  </div>

                  <div style={styles.slotActions}>
                    {idx > 0 && (
                      <button
                        type="button"
                        style={styles.actionBtn}
                        onClick={() => handleSave(idx)}
                        disabled={busy}
                      >
                        Save
                      </button>
                    )}
                    {meta && (
                      <button
                        type="button"
                        style={styles.actionBtn}
                        onClick={() => setConfirm({ type: 'load', slot: idx })}
                        disabled={busy}
                      >
                        Load
                      </button>
                    )}
                    {idx > 0 && meta && (
                      <button
                        type="button"
                        style={{ ...styles.actionBtn, color: colors.warning }}
                        onClick={() => setConfirm({ type: 'delete', slot: idx })}
                        disabled={busy}
                      >
                        Delete
                      </button>
                    )}
                  </div>

                  {confirm && confirm.slot === idx && (
                    <div style={styles.confirmBar}>
                      <span style={styles.confirmText}>
                        {confirm.type === 'load' ? 'Load this save? Current progress will be lost.' : 'Delete this save?'}
                      </span>
                      <button type="button" style={styles.confirmYes} onClick={confirmAction} disabled={busy}>
                        Yes
                      </button>
                      <button type="button" style={styles.confirmNo} onClick={() => setConfirm(null)}>
                        Cancel
                      </button>
                    </div>
                  )}
                </div>
              ))}
            </div>

            <div style={styles.footer}>
              <button type="button" style={styles.footerBtn} onClick={handleExport}>
                Export JSON
              </button>
              <button type="button" style={styles.footerBtn} onClick={handleImport}>
                Import JSON
              </button>
            </div>
          </>
        )}

        {/* Ledger tab */}
        {tab === 'ledger' && (
          <div style={styles.ledgerContainer}>
            {ledger.length === 0 ? (
              <p style={styles.ledgerEmpty}>
                No ledger entries yet. The trail scribe composes a summary every five days.
              </p>
            ) : (
              ledger.slice().reverse().map((entry, reverseIdx) => {
                const idx = ledger.length - 1 - reverseIdx;
                const expanded = expandedEntry === idx;
                return (
                  <LedgerCard
                    key={idx}
                    entry={entry}
                    expanded={expanded}
                    onToggle={() => setExpandedEntry(expanded ? null : idx)}
                  />
                );
              })
            )}
          </div>
        )}
      </div>
    </div>
  );
}

// ============================================================
// LEDGER CARD COMPONENT
// ============================================================

function LedgerCard({
  entry,
  expanded,
  onToggle,
}: {
  entry: LedgerEntry;
  expanded: boolean;
  onToggle: () => void;
}) {
  return (
    <div style={styles.ledgerCard}>
      <button
        type="button"
        style={styles.ledgerHeader}
        onClick={onToggle}
      >
        <div style={styles.ledgerHeaderLeft}>
          <span style={styles.ledgerPeriod}>{entry.period}</span>
          <span style={styles.ledgerAct}>{entry.act}</span>
        </div>
        <span style={styles.ledgerChevron}>{expanded ? '\u25B2' : '\u25BC'}</span>
      </button>

      {expanded && (
        <div style={styles.ledgerBody}>
          {/* Major Events */}
          {entry.majorEvents.length > 0 && (
            <div style={styles.ledgerSection}>
              <span style={styles.ledgerSectionLabel}>Key Events</span>
              <ul style={styles.ledgerList}>
                {entry.majorEvents.map((evt, i) => (
                  <li key={i} style={styles.ledgerListItem}>{evt}</li>
                ))}
              </ul>
            </div>
          )}

          {/* Emotional Arc */}
          {entry.emotionalArc && (
            <div style={styles.ledgerSection}>
              <span style={styles.ledgerSectionLabel}>Mood</span>
              <p style={styles.ledgerArcText}>{entry.emotionalArc}</p>
            </div>
          )}

          {/* Losses & Gains */}
          {entry.lossesAndGains.length > 0 && (
            <div style={styles.ledgerSection}>
              <span style={styles.ledgerSectionLabel}>Changes</span>
              <ul style={styles.ledgerList}>
                {entry.lossesAndGains.map((item, i) => (
                  <li key={i} style={styles.ledgerListItem}>{item}</li>
                ))}
              </ul>
            </div>
          )}

          {/* Active Threads */}
          {entry.activeThreads.length > 0 && (
            <div style={styles.ledgerSection}>
              <span style={styles.ledgerSectionLabel}>Open Threads</span>
              {entry.activeThreads.map((thread) => (
                <div key={thread.id} style={styles.ledgerThread}>
                  <span style={styles.ledgerThreadDesc}>{thread.description}</span>
                  <span style={{
                    ...styles.ledgerThreadStatus,
                    color: thread.status === 'escalating' ? colors.warning : colors.textMuted,
                  }}>
                    {thread.status}
                  </span>
                </div>
              ))}
            </div>
          )}

          {/* Relationships */}
          {entry.relationships.length > 0 && (
            <div style={styles.ledgerSection}>
              <span style={styles.ledgerSectionLabel}>Relationships</span>
              {entry.relationships.map((rel) => (
                <div key={rel.companion} style={styles.ledgerRelRow}>
                  <span style={styles.ledgerRelName}>{rel.companion}</span>
                  <span style={styles.ledgerRelLoyalty}>Loyalty: {rel.loyalty}</span>
                  {rel.recentBond && (
                    <span style={styles.ledgerRelDetail}>{rel.recentBond}</span>
                  )}
                  {rel.recentTension && (
                    <span style={{ ...styles.ledgerRelDetail, color: colors.warning }}>
                      {rel.recentTension}
                    </span>
                  )}
                </div>
              ))}
            </div>
          )}

          {/* Pending Consequences */}
          {entry.pendingConsequences.length > 0 && (
            <div style={styles.ledgerSection}>
              <span style={styles.ledgerSectionLabel}>Looming</span>
              {entry.pendingConsequences.map((pc, i) => (
                <div key={i} style={styles.ledgerConsequence}>
                  <span style={styles.ledgerConsequenceText}>{pc.consequence}</span>
                  {pc.foreshadowed && (
                    <span style={styles.ledgerForeshadowed}>foreshadowed</span>
                  )}
                </div>
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  );
}

// ============================================================
// STYLES
// ============================================================

const styles: Record<string, React.CSSProperties> = {
  overlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'rgba(26, 26, 26, 0.6)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1200,
  },
  card: {
    background: colors.card,
    border: `2px solid ${colors.primary}`,
    borderRadius: '8px',
    padding: '24px 32px',
    maxWidth: '560px',
    width: '90%',
    maxHeight: '80vh',
    overflowY: 'auto' as const,
    boxShadow: '0 8px 32px rgba(0,0,0,0.4)',
    fontFamily: "'Crimson Text', Georgia, serif",
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '12px',
  },
  title: {
    fontSize: '22px',
    fontWeight: 700,
    color: colors.primaryDark,
    margin: 0,
  },
  closeBtn: {
    background: 'none',
    border: 'none',
    fontSize: '18px',
    fontWeight: 700,
    color: colors.primary,
    cursor: 'pointer',
    fontFamily: "'Crimson Text', Georgia, serif",
  },

  // Tab bar
  tabBar: {
    display: 'flex',
    gap: '0px',
    marginBottom: '16px',
    borderBottom: `1px solid ${colors.secondary}`,
  },
  tab: {
    flex: 1,
    padding: '8px 12px',
    background: 'none',
    border: 'none',
    borderBottom: '2px solid transparent',
    cursor: 'pointer',
    fontSize: '15px',
    fontFamily: "'Crimson Text', Georgia, serif",
    color: colors.textMuted,
    fontWeight: 500,
  },
  tabActive: {
    flex: 1,
    padding: '8px 12px',
    background: 'none',
    border: 'none',
    borderBottom: `2px solid ${colors.primary}`,
    cursor: 'pointer',
    fontSize: '15px',
    fontFamily: "'Crimson Text', Georgia, serif",
    color: colors.primaryDark,
    fontWeight: 700,
  },

  // Saves tab
  slotList: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '12px',
    marginBottom: '16px',
  },
  slotRow: {
    background: colors.button,
    border: `1px solid ${colors.secondary}`,
    borderRadius: '4px',
    padding: '12px 16px',
  },
  slotInfo: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '4px',
    marginBottom: '8px',
  },
  slotLabel: {
    fontSize: '15px',
    fontWeight: 600,
    color: colors.primaryDark,
  },
  slotMeta: {
    fontSize: '13px',
    color: colors.textSecondary,
    lineHeight: '1.4',
  },
  slotEmpty: {
    fontSize: '13px',
    color: '#999',
    fontStyle: 'italic',
  },
  slotActions: {
    display: 'flex',
    gap: '8px',
  },
  actionBtn: {
    padding: '4px 12px',
    background: colors.card,
    border: `1px solid ${colors.secondary}`,
    borderRadius: '3px',
    cursor: 'pointer',
    fontSize: '13px',
    fontFamily: "'Crimson Text', Georgia, serif",
    color: colors.primaryDark,
  },
  confirmBar: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginTop: '8px',
    padding: '8px',
    background: '#faf3e0',
    borderRadius: '3px',
    border: '1px solid #d4a017',
  },
  confirmText: {
    fontSize: '13px',
    color: colors.textSecondary,
    flex: 1,
  },
  confirmYes: {
    padding: '4px 12px',
    background: colors.primary,
    border: 'none',
    borderRadius: '3px',
    cursor: 'pointer',
    fontSize: '13px',
    fontFamily: "'Crimson Text', Georgia, serif",
    color: colors.card,
  },
  confirmNo: {
    padding: '4px 12px',
    background: colors.card,
    border: `1px solid ${colors.secondary}`,
    borderRadius: '3px',
    cursor: 'pointer',
    fontSize: '13px',
    fontFamily: "'Crimson Text', Georgia, serif",
    color: colors.primaryDark,
  },
  footer: {
    display: 'flex',
    gap: '8px',
    justifyContent: 'center',
    borderTop: `1px solid ${colors.secondary}`,
    paddingTop: '12px',
  },
  footerBtn: {
    padding: '6px 16px',
    background: colors.button,
    border: `1px solid ${colors.secondary}`,
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '14px',
    fontFamily: "'Crimson Text', Georgia, serif",
    color: colors.primaryDark,
  },

  // Ledger tab
  ledgerContainer: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '10px',
  },
  ledgerEmpty: {
    fontSize: '14px',
    color: colors.textMuted,
    fontStyle: 'italic',
    textAlign: 'center' as const,
    padding: '24px 0',
    lineHeight: '1.5',
  },
  ledgerCard: {
    background: colors.button,
    border: `1px solid ${colors.secondary}`,
    borderRadius: '4px',
    overflow: 'hidden',
  },
  ledgerHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    padding: '10px 14px',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontFamily: "'Crimson Text', Georgia, serif",
    textAlign: 'left' as const,
  },
  ledgerHeaderLeft: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '2px',
  },
  ledgerPeriod: {
    fontSize: '15px',
    fontWeight: 700,
    color: colors.primaryDark,
  },
  ledgerAct: {
    fontSize: '12px',
    color: colors.textMuted,
    fontStyle: 'italic',
  },
  ledgerChevron: {
    fontSize: '10px',
    color: colors.textMuted,
  },
  ledgerBody: {
    padding: '0 14px 12px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '10px',
    borderTop: `1px solid ${colors.borderLight}`,
  },
  ledgerSection: {
    marginTop: '6px',
  },
  ledgerSectionLabel: {
    fontSize: '11px',
    fontWeight: 700,
    color: colors.secondaryDark,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.8px',
    display: 'block',
    marginBottom: '4px',
  },
  ledgerList: {
    margin: '0',
    paddingLeft: '16px',
  },
  ledgerListItem: {
    fontSize: '13px',
    color: colors.textBody,
    lineHeight: '1.5',
    marginBottom: '2px',
  },
  ledgerArcText: {
    fontSize: '13px',
    color: colors.textBody,
    fontStyle: 'italic',
    margin: '0',
    lineHeight: '1.5',
  },
  ledgerThread: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    gap: '8px',
    padding: '2px 0',
  },
  ledgerThreadDesc: {
    fontSize: '13px',
    color: colors.textBody,
    flex: 1,
  },
  ledgerThreadStatus: {
    fontSize: '11px',
    fontStyle: 'italic',
    textTransform: 'capitalize' as const,
    flexShrink: 0,
  },
  ledgerRelRow: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    alignItems: 'baseline',
    gap: '6px',
    padding: '2px 0',
  },
  ledgerRelName: {
    fontSize: '13px',
    fontWeight: 600,
    color: colors.primaryDark,
  },
  ledgerRelLoyalty: {
    fontSize: '12px',
    color: colors.textMuted,
  },
  ledgerRelDetail: {
    fontSize: '12px',
    color: colors.textSecondary,
    fontStyle: 'italic',
  },
  ledgerConsequence: {
    display: 'flex',
    alignItems: 'baseline',
    gap: '6px',
    padding: '2px 0',
  },
  ledgerConsequenceText: {
    fontSize: '13px',
    color: colors.textBody,
    flex: 1,
  },
  ledgerForeshadowed: {
    fontSize: '10px',
    color: colors.secondaryDark,
    fontStyle: 'italic',
    flexShrink: 0,
  },
};
