/**
 * Frontier — Encounter System Interfaces
 *
 * Per GDD §6: Encounter types and the Devil's Bargain hard-coded table.
 * Encounters are generated by Game Logic, resolved by Game Logic,
 * and narrated by the Narrator. The Narrator never generates encounters.
 */

// ============================================================
// ENCOUNTER TYPES
// ============================================================

export enum EncounterType {
  Trail = 'trail',
  Settlement = 'settlement',
  Hostile = 'hostile',
  Environmental = 'environmental',
  Discovery = 'discovery',
  Party = 'party',
  Desperate = 'desperate',
}

export interface Encounter {
  id: string;
  type: EncounterType;
  name: string;
  description: string;
  /** What triggered this encounter */
  trigger: EncounterTrigger;
  /** Player choices available */
  choices: EncounterChoice[];
  /** Whether this encounter has been resolved */
  resolved: boolean;
  /** Outcome after resolution */
  outcome: EncounterOutcome | null;
}

export interface EncounterTrigger {
  type: 'distance' | 'waypoint' | 'territory' | 'weather' | 'scout' | 'morale' | 'critical';
  /** Zone or condition that triggered it */
  condition: string;
}

export interface EncounterChoice {
  id: string;
  label: string;
  description: string;
  /** Requirements to select this choice */
  requirements?: EncounterRequirement[];
  /** Whether this choice is currently available */
  available: boolean;
}

export interface EncounterRequirement {
  type: 'supply' | 'equipment' | 'companion' | 'skill' | 'morale';
  key: string;
  minValue?: number;
}

export interface EncounterOutcome {
  choiceId: string;
  description: string;
  effects: EncounterEffect[];
}

export interface EncounterEffect {
  type: 'supply' | 'health' | 'morale' | 'loyalty' | 'equipment' | 'companion' | 'route' | 'time' | 'transport';
  target: string;
  delta: number | string;
}

// ============================================================
// DEVIL'S BARGAIN (per GDD §3.9)
// ============================================================

/**
 * Hard-coded lookup table. NOT AI-generated.
 * Costs target highest-value assets to prevent exploitation.
 * Limited to 3 total uses per playthrough.
 */
export interface DevilsBargainEntry {
  crisis: string;
  encounter: string;
  cost: DevilsBargainCost;
}

export interface DevilsBargainCost {
  description: string;
  /** The mechanical effects of accepting */
  effects: EncounterEffect[];
}

export const DEVILS_BARGAIN_TABLE: DevilsBargainEntry[] = [
  {
    crisis: 'Water zero, distant from source',
    encounter: 'Comanchero trader',
    cost: {
      description: 'LOSE: Rifle (hunting = 0, defense -= 50)',
      effects: [
        { type: 'equipment', target: 'rifle', delta: -100 },
        { type: 'supply', target: 'ammo', delta: 'zero' },
      ],
    },
  },
  {
    crisis: 'Water zero, no rifle',
    encounter: 'Comanchero (alt)',
    cost: {
      description: 'LOSE: 100% tradeGoods + fortSumnerDebt flag',
      effects: [
        { type: 'supply', target: 'tradeGoods', delta: 'zero' },
        { type: 'route', target: 'fortSumnerDebt', delta: 'true' },
      ],
    },
  },
  {
    crisis: 'Horse death',
    encounter: 'Army patrol',
    cost: {
      description: 'LOSE: All ammo + forced detour (+40 miles)',
      effects: [
        { type: 'supply', target: 'ammo', delta: 'zero' },
        { type: 'route', target: 'detour', delta: '40' },
      ],
    },
  },
  {
    crisis: 'Critical injury, no medical',
    encounter: 'Traveling bone-setter',
    cost: {
      description: 'LOSE: All money OR companion.loyalty -= 40',
      effects: [
        { type: 'supply', target: 'funds', delta: 'zero' },
      ],
    },
  },
  {
    crisis: 'Party morale zero',
    encounter: 'Unplanned settlement',
    cost: {
      description: 'LOSE: 2 days, but morale → 50, partial resupply',
      effects: [
        { type: 'time', target: 'days', delta: '2' },
        { type: 'morale', target: 'player', delta: 'set:50' },
      ],
    },
  },
];

export const MAX_FAIL_FORWARDS = 3;
